# fly.toml file generated for restore on 2023-02-09T10:54:56+07:00

app = "restore"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "trycatchlearn/restore:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  StripeSettings__PublishableKey="pk_test_51JV6ejEiX6mroRZ6LZfplGw2mBnYSq6Jvj0T927DOTLH7nqQbSKXYDmuB1RsaVPitHEJEYo1cz5Dd8Naagiaxe5X00OqnaFoUY"
  Cloudinary__CloudName="dj3wmuy3l"
  Cloudinary__ApiKey="895484589483755"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
